ViewModels/Respondent/PocViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ASJ.Models;
using ASJ.Models.Form;

namespace ASJ.ViewModels.Respondent
{
    public class PocViewModel
    {
        [Required(ErrorMessage = "Agency Name or ID is required")]
        public string Agency { get; set; }
        public int OrganizationId { get; set; }
        public int Year { get; set; }
        public string State { get; set; }
        public string UserName { get; set; }
        public OrganizationFollowup Followup { get; set; }
        public int InstrumentId { get; set; }
        public LookupAgencyStatus LookupAgencyStatus { get; set; }
        public LookupOrganizationType OrganizationType { get; set; }
        public Response Response { get; set; }
        public string dataStatus { get; set; }

    }
}

Controllers/RespondentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ASJ.ViewModels.Respondent;
using ASJ.ViewModels.Client;
using ASJ.Models;
using ASJ.ClassObjects;
using static ASJ.Startup;
using ASJ.Utils;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authorization;
using ASJ.Models.Form;

namespace ASJ.Controllers
{
    [Authorize]
    public class RespondentController : BaseController
    {
        private ASJDbContext dataContext;
        private ASJLegacyContext legacyContext;
        public int referenceYear;
        private readonly ApplicationVariables _appVariables;
        private readonly IHostingEnvironment _hostingEnvironment;

        public RespondentController(ASJDbContext dbContext, ASJLegacyContext legContext, IHostingEnvironment HostingEnvironment, IOptions<ApplicationVariables> appVariables)
        {
            this.dataContext = dbContext;
            legacyContext = legContext;
            _appVariables = appVariables.Value;
            this.referenceYear = Int32.Parse(_appVariables.ReferenceYear);
            _hostingEnvironment = HostingEnvironment;

        }

        public IActionResult Index()
        {   
            List<PocViewModel> models = (from x in dataContext.Organizations
                         .Include(x => x.OrganizationType).Include(x => x.Responses).Include(x => x.Responses)
                         where (x.UserName == @User.Identity.Name)
                                  select new PocViewModel()
                                  {
                                        Agency = x.Name,
                                        OrganizationId = x.OrganizationId,
                                        Year = x.Year,
                                        State = x.State,
                                        UserName = x.UserName,
                                        //LookupAgencyStatus = x.OrganizationFollowup.AgencyStatusCode,
                                        //Followup = x.OrganizationFollowup,
                                        OrganizationType = x.OrganizationType
                                  }).OrderByDescending(o => o.Year).ToList();

            foreach (var m in models)
            {
                m.Followup = dataContext.OrganizationFollowups.Where(p => p.Organization.OrganizationId == m.OrganizationId && p.Organization.Year == m.Year).FirstOrDefault();
                m.LookupAgencyStatus = m.Followup.AgencyStatusCode;
                //set the responses for the model by getting the instrument id based on the org type
                InstrumentOrganizationType instr = dataContext.InstrumentOrganizationTypes.FirstOrDefault(x => x.InstrumentYear == Convert.ToInt32(m.Year) && x.OrganizationTypeId == Convert.ToInt32(m.OrganizationType.OrganizationTypeId));
                if (instr != null)
                {
                    m.InstrumentId = instr.InstrumentId;
                    m.Response = dataContext.Responses.FirstOrDefault(p => p.Organization.OrganizationId == m.OrganizationId && p.InstrumentId == instr.InstrumentId && p.ResponseVariable == "iDQFUFlag");
                }

                

                switch (m.Year)
                {
                    case 2015:
                        var asjForm2015 = legacyContext.AsjAnnual2015
                              .Where(o => o.OrganizationId == m.OrganizationId).FirstOrDefault();
                        if (asjForm2015 != null)
                        {
                            m.dataStatus = Extensions.dataStatusDesc(asjForm2015.FormStatus);
                            if (FormController.GetLastPage(this.dataContext, m.InstrumentId, m.OrganizationId, m.Year) >= 15)
                                m.dataStatus = "Final";
                        }
                        else
                        {
                            m.dataStatus = "Not Started";
                        }
                        break;

                    case 2016:
                        var asjForm2016 = legacyContext.AsjAnnual2016
                              .Where(o => o.OrganizationId == m.OrganizationId).FirstOrDefault();
                        if (asjForm2016 != null)
                        {
                            m.dataStatus = Extensions.dataStatusDesc(asjForm2016.FormStatus);
                            if (FormController.GetLastPage(this.dataContext, m.InstrumentId, m.OrganizationId, m.Year) >= 15)
                                m.dataStatus = "Final";
                        }
                        else
                        {
                            m.dataStatus = "Not Started";
                        }
                        break;

                    case 2017:
                        var asjForm2017 = legacyContext.AsjAnnual2017
                              .Where(o => o.OrganizationId == m.OrganizationId).FirstOrDefault();
                        if (asjForm2017 != null)
                        {
                            m.dataStatus = Extensions.dataStatusDesc(asjForm2017.FormStatus);
                            if (FormController.GetLastPage(this.dataContext, m.InstrumentId, m.OrganizationId, m.Year) >= 15)
                                m.dataStatus = "Final";
                        }
                        else
                        {
                            m.dataStatus = "Not Started";
                        }
                        break;

                    case 2018:
                        var asjForm2018 = dataContext.PDFAnnualASJs
                              .Where(o => o.OrganizationId == m.OrganizationId).FirstOrDefault();
                        if (asjForm2018 != null)
                        {
                            m.dataStatus = Extensions.dataStatusDesc(asjForm2018.form_status);
                            if (FormController.GetLastPage(this.dataContext, m.InstrumentId, m.OrganizationId, m.Year) >= 15)
                                m.dataStatus = "Final";
                        }
                        else
                        {
                            m.dataStatus = "Not Started";
                        }
                        break;

                    case 2019:
                        var asjForm2019 = dataContext.PDFAnnualASJs
                              .Where(o => o.OrganizationId == m.OrganizationId).FirstOrDefault();
                        if (asjForm2019 != null)
                        {
                            m.dataStatus = Extensions.dataStatusDesc(asjForm2019.form_status);
                            if (FormController.GetLastPage(this.dataContext, m.InstrumentId, m.OrganizationId, m.Year) >= 15)
                                m.dataStatus = "Final";
                        }
                        else
                        {
                            m.dataStatus = "Not Started";
                        }
                        break;
                }

                //do something else for cognitive
                if(m.OrganizationType.Description.Contains("Cognitive"))
                {
                    string sql = "SELECT * FROM dbo.pivot_responses_cogtest WHERE organizationid = " + m.OrganizationId.ToString();
                    var cogForm = (from pd in dataContext.PDFCognitives
                                   .FromSql(sql)
                                   select new DataCollectionViewModel()
                                   {
                                       OrganizationId = m.OrganizationId,
                                       Year = m.Year,
                                       InstrumentId = m.InstrumentId,
                                       form_status = "In Progress",
                                   }).FirstOrDefault();

                    if (cogForm != null)
                    {
                        m.dataStatus = "In Progress";

                        //hardcoding the last page number and a new status
                        //get last page of the instrument
                        int maxPage = dataContext.InstrumentQuestions.OrderByDescending(p => p.Page).Where(p => p.Instrument.InstrumentId == m.InstrumentId).AsNoTracking().FirstOrDefault().Page;
                        if (FormController.GetLastPage(this.dataContext, m.InstrumentId, m.OrganizationId, m.Year) >= maxPage)
                            m.dataStatus = "Final";
                    }
                    else
                    {
                        m.dataStatus = "Not Started";
                    }
                }
                ViewBag.OrganizationID = m.OrganizationId;
                if (m.Year == referenceYear)
                    ViewBag.InstrumentId = m.InstrumentId;
            }

            Organization org = (from o in dataContext.Organizations
                                where o.OrganizationId == models[0].OrganizationId
                                    && o.Year == referenceYear
                                select o).FirstOrDefault();
            Instrument inst = (from i in dataContext.Instruments
                               where i.InstrumentId == org.InstrumentId
                               select i).FirstOrDefault();

            ASJ.ViewModels.Form.DataSupplierViewModel dsbvm = new ASJ.ViewModels.Form.DataSupplierViewModel();
            dsbvm.Organization = org;
            dsbvm.Instrument = inst;

            var ds = dataContext.DataSuppliers.Where(s => s.Organization == org && s.Instrument == inst)
                .FirstOrDefault();

            if (ds != null)
            {
                dsbvm.DataSupplierId = ds.DataSupplierId;
                dsbvm.Address = ds.Address;
                dsbvm.City = ds.City;
                dsbvm.email = ds.email;
                dsbvm.Fax = ds.Fax;
                dsbvm.Name = ds.Name;

Views/Respondent/Index.cshtml
@model List<ASJ.ViewModels.Respondent.PocViewModel>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    if (Context.Request.Host.Host.Contains("jailsurvey"))
    {
        Layout = "~/Views/Shared/_LayoutCogTest.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}
@{
    ViewData["Title"] = "POC Home";
}
@if (Context.Request.Host.Host.Contains("jailsurvey"))
{
    <style>

        div#content-body {
            height: 100%;
            position: relative;
            margin-bottom: 140px;
        }
    </style>
}

else
{
    <style>

        div#content-body {
            overflow: auto;
            height: 100%;
            position: relative;
            margin-bottom: 140px;
        }
    </style>
}

<style>

    .agencyheader {
        width: 40%;
    }

    table {
        border: 1px solid;
        width: 100%;
        font-size: 1.25em;
    }

    th {
        background-color: rgba(153, 153, 153, 1)
    }

    th, td {
        padding: 5px 10px;
        border: 1px solid;
    }

    a:link.tbl_link {
        color: blue;
        text-decoration: underline;
    }

    a.btn {
        color: white;
        text-decoration: none;
        font-size: 1em;
    }

    table, td {
        border: none;
    }
</style>
<div class="container">
    <div class="row center">
        <div class="center-block agencyheader">
            <div id="org_name">
                <h4>@Model[0].Agency - @Model[0].State <small> (@Model[0].OrganizationId)</small></h4>
            </div>
        </div>
    </div><br />




    <div class="row center">
        <div class="center-block w-50p">
            <table class="table table-hover">
                @*<thead>
                        <tr class="blue-head">
                            <th style="width: 175px;">Year</th>
                            <th>Due</th>
                            @if (!Context.Request.Host.Host.Contains("jailsurvey"))
                            {
                                <th>Data Status</th>
                                <th>Data Quality</th>
                             }
                            <th> </th>
                            <th>PDF</th>
                        </tr>
                    </thead>*@
                <tbody>
                    <tr>
                        @if (@Model.Count > 0)
                        {
                            var startIndex = 0;
                            @if (@Model[0].Year == @ViewBag.referenceYear)
                            {
                                //Display currrent data collection if exist
                            <tr>
                                <td>@Model[0].Year</td>
                                @if (@Model[0].dataStatus == "Not Started")
                                {
                                    <td><a id="start_form" href="@Url.Action("Instructions", "Form", new { instrumentId =  Model[0].InstrumentId, organizationId = Model[0].OrganizationId, year = @ViewBag.referenceYear })" class="btn btn-primary btn-sm">Enter Data</a></td>
                                    <td>&nbsp;</td>
                                    <td><a href="@Url.Action("ExportPDF", "Respondent", new { instrumentId = @Model[0].InstrumentId, organizationId = @Model[0].OrganizationId, year = @Model[0].Year })" target="_blank" class="btn btn-primary btn-sm">View form</a></td>
                                    <td>&nbsp;</td>

                                }
                                else if (@Model[0].dataStatus == "Final")
                                {
                                    <td><a id="start_form" href="@Url.Action("Instructions", "Form", new { instrumentId =  Model[0].InstrumentId, organizationId = Model[0].OrganizationId, year = @ViewBag.referenceYear })" class="btn btn-primary btn-sm">Enter Data</a></td>
                                    <td>&nbsp;</td>
                                    <td><a href="@Url.Action("ExportPDF", "Respondent", new { instrumentId = @Model[0].InstrumentId, organizationId = @Model[0].OrganizationId, year = @Model[0].Year })" target="_blank" class="btn btn-primary btn-sm">View form</a></td>
                                    <td>
                                        @if (Model[0].Response != null && Model[0].Response.ResponseVariable == "iDQFUFlag" && Model[0].Response.ResponseValue == "True")
                                        {
                                            <a href="@Url.Action("Index", "DQFU", new { organizationId = @Model[0].OrganizationId, iid = @Model[0].InstrumentId })" class="btn btn-primary btn-sm">Compare data</a>
                                        }
                                    </td>
                                }
                                else
                                {
                                    <td><a id="start_form" href="@Url.Action("Instructions", "Form", new { instrumentId =  Model[0].InstrumentId, organizationId = Model[0].OrganizationId, year = @ViewBag.referenceYear })" class="btn btn-primary btn-sm">Enter Data</a></td>
                                    <td><a id="resume_form" href="@Url.Action("Index", "Form", new { instrumentId = @Model[0].InstrumentId, organizationId = @Model[0].OrganizationId, year = @Model[0].Year, resume=true })" class="btn btn-primary btn-sm">Resume</a></td>
                                    <td><a href="@Url.Action("ExportPDF", "Respondent", new { instrumentId = @Model[0].InstrumentId, organizationId = @Model[0].OrganizationId, year = @Model[0].Year })" target="_blank" class="btn btn-primary btn-sm">View form</a></td>
                                    <td>
                                        @if (Model[0].Response != null && Model[0].Response.ResponseVariable == "iDQFUFlag" && Model[0].Response.ResponseValue == "True")
                                        {
                                            <a href="@Url.Action("Index", "DQFU", new { organizationId = @Model[0].OrganizationId, iid = @Model[0].InstrumentId })" class="btn btn-primary btn-sm">Compare data</a>
                                        }
                                    </td>
                                }
                            </tr>
                            startIndex = 1;
                        }
                        @* Display past data collection *@
                            @for (int i = startIndex; i <= @Model.Count - 1; i++)
                            {
                                <tr>
                                    <td>@Model[i].Year</td>
                                    @if (@Model[i].dataStatus != "Not Started")
                                    {
                                        <td colspan="2">Closed</td>
                                        <td><a href="@Url.Action("ExportPDF", "Respondent", new { instrumentId = @Model[i].InstrumentId, organizationId = @Model[i].OrganizationId, year = @Model[i].Year })" target="_blank" class="btn btn-primary btn-sm">View form</a></td>
                                    }
                                    else
                                    {
                                        <td>@Model[i].dataStatus</td>

                                        <td></td>
                                    }
                                    <td></td>
                                </tr>
                            }

                        }
                        else
                        {
                            @* No data collection, put out a blank line *@
                            <tr><td colspan="4">&nbsp;</td></tr>
                        }
                    </tbody>
                </table>

            </div><!--end .col-sm-12-->
        </div><!--end row-->
        @Html.Partial("_DataSuppliedBy", (ASJ.ViewModels.Form.DataSupplierViewModel)ViewBag.DatasupplierVM)
    </div><!--end container-->



    <script>
        $(document).ready(function () {
            //The menu option 'Enter Data' will trigger relevant start_form link.
            $("#poc_submit_data").click(function () {
                $("#start_form")[0].click();
            });
        });
    </script>